// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"

	v1 "github.com/fi-ts/accounting-go/pkg/apis/v1"
)

// S3ServiceClient is an autogenerated mock type for the S3ServiceClient type
type S3ServiceClient struct {
	mock.Mock
}

// BucketStats provides a mock function with given fields: ctx, in, opts
func (_m *S3ServiceClient) BucketStats(ctx context.Context, in *v1.S3BucketReport, opts ...grpc.CallOption) (*v1.Empty, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *v1.Empty
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.S3BucketReport, ...grpc.CallOption) (*v1.Empty, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.S3BucketReport, ...grpc.CallOption) *v1.Empty); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.Empty)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.S3BucketReport, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Usage provides a mock function with given fields: ctx, in, opts
func (_m *S3ServiceClient) Usage(ctx context.Context, in *v1.S3UsageRequest, opts ...grpc.CallOption) (*v1.S3UsageResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 *v1.S3UsageResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *v1.S3UsageRequest, ...grpc.CallOption) (*v1.S3UsageResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *v1.S3UsageRequest, ...grpc.CallOption) *v1.S3UsageResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*v1.S3UsageResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *v1.S3UsageRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewS3ServiceClient interface {
	mock.TestingT
	Cleanup(func())
}

// NewS3ServiceClient creates a new instance of S3ServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewS3ServiceClient(t mockConstructorTestingTNewS3ServiceClient) *S3ServiceClient {
	mock := &S3ServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
