// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeInfoServiceServer is an autogenerated mock type for the UnsafeInfoServiceServer type
type UnsafeInfoServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedInfoServiceServer provides a mock function with given fields:
func (_m *UnsafeInfoServiceServer) mustEmbedUnimplementedInfoServiceServer() {
	_m.Called()
}

type NewUnsafeInfoServiceServerT interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeInfoServiceServer creates a new instance of UnsafeInfoServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeInfoServiceServer(t NewUnsafeInfoServiceServerT) *UnsafeInfoServiceServer {
	mock := &UnsafeInfoServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
