// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeClusterServiceServer is an autogenerated mock type for the UnsafeClusterServiceServer type
type UnsafeClusterServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedClusterServiceServer provides a mock function with given fields:
func (_m *UnsafeClusterServiceServer) mustEmbedUnimplementedClusterServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafeClusterServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeClusterServiceServer creates a new instance of UnsafeClusterServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeClusterServiceServer(t mockConstructorTestingTNewUnsafeClusterServiceServer) *UnsafeClusterServiceServer {
	mock := &UnsafeClusterServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
