// Code generated by mockery v2.22.1. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafePostgresServiceServer is an autogenerated mock type for the UnsafePostgresServiceServer type
type UnsafePostgresServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedPostgresServiceServer provides a mock function with given fields:
func (_m *UnsafePostgresServiceServer) mustEmbedUnimplementedPostgresServiceServer() {
	_m.Called()
}

type mockConstructorTestingTNewUnsafePostgresServiceServer interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafePostgresServiceServer creates a new instance of UnsafePostgresServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafePostgresServiceServer(t mockConstructorTestingTNewUnsafePostgresServiceServer) *UnsafePostgresServiceServer {
	mock := &UnsafePostgresServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
