// Code generated by mockery v2.12.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeVolumeServiceServer is an autogenerated mock type for the UnsafeVolumeServiceServer type
type UnsafeVolumeServiceServer struct {
	mock.Mock
}

// mustEmbedUnimplementedVolumeServiceServer provides a mock function with given fields:
func (_m *UnsafeVolumeServiceServer) mustEmbedUnimplementedVolumeServiceServer() {
	_m.Called()
}

type NewUnsafeVolumeServiceServerT interface {
	mock.TestingT
	Cleanup(func())
}

// NewUnsafeVolumeServiceServer creates a new instance of UnsafeVolumeServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUnsafeVolumeServiceServer(t NewUnsafeVolumeServiceServerT) *UnsafeVolumeServiceServer {
	mock := &UnsafeVolumeServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
