---
name: Build Action
on:
  pull_request:
    branches:
      - main
  release:
    types:
      - published
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.21
      uses: actions/setup-go@v4
      with:
        go-version: "1.21"
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: setup buf
      uses: bufbuild/buf-setup-action@v1

    - name: make
      run: |
        make
        make check-diff

    - uses: release-drafter/release-drafter@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}